//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elga_Xizmat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adses
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Rubric_Id { get; set; }
        public Nullable<int> TypeProduct_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Short_text { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public Nullable<int> Area_Id { get; set; }
        public string Picture { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> State_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CountView { get; set; }
        public Nullable<int> TypeAdses { get; set; }
    }
}
