//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elga_Xizmat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NeedCountView { get; set; }
        public Nullable<int> NeedDayCount { get; set; }
        public Nullable<int> StateID { get; set; }
        public string FilePath { get; set; }
    }
}
