//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elga_Xizmat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        public int Id { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public string AreaNameUzb { get; set; }
        public string AreaNameRu { get; set; }
    }
}
