//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elga_Xizmat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELX_DBEntities : DbContext
    {
        public ELX_DBEntities()
            : base("name=ELX_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Adses> Adses { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Rubric> Rubric { get; set; }
        public virtual DbSet<Type_Product> Type_Product { get; set; }
        public virtual DbSet<StateProduct> StateProduct { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<TypeAdses> TypeAdses { get; set; }
        public virtual DbSet<Advert> Adverts { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
