//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elga_Xizmat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string User_Name { get; set; }
        public Nullable<decimal> Phone_number { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> State { get; set; }
    }
}
